spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
  main:
    lazy-initialization: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  info:
    title: Allegro Style Cart API
    description: REST API for the Allegro Style Cart Application
    version: 1.0.0
