spring:
  application:
    name: allegro-style-cart-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
  main:
    lazy-initialization: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  info:
    title: Allegro Style Cart API
    description: REST API for the Allegro Style Cart Application
    version: 1.0.0

# Actuator and Observability Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
  metrics:
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 400ms, 500ms, 1s
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:dev}
  prometheus:
    metrics:
      export:
        enabled: true

