spring:
  application:
    name: allegro-cart-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
  main:
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 250ms, 400ms, 500ms, 1s, 2s
    enable:
      jvm: true
      process: true
      system: true
      http: true
  observations:
    http:
      server:
        requests:
          name: http.server.requests

logging:
  pattern:
    console: |
      {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%level","service":"${spring.application.name}","environment":"%X{environment:-default}","requestId":"%X{requestId:-}","route":"%X{route:-}","thread":"%thread","logger":"%logger{36}","message":"%msg","exception":"%ex{full}"}
  level:
    root: INFO
    com.github.pigeon: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    com.github.pigeon: INFO
