spring:
  application:
    name: allegro-cart-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
  main:
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}","level":"%level","service":"${spring.application.name}","thread":"%thread","logger":"%logger{36}","message":"%msg","exception":"%ex{full}"}%n'
  level:
    root: INFO
    com.github.pigeon: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    com.github.pigeon: INFO
